/**
 * Generated by @openapi-codegen
 *
 * @version 1.1
 */
export type CreateTaskDto = {
  /**
   * El titúlo de la tarea
   */
  title: string;
  /**
   * La descripción de la tarea
   */
  description: string;
};

export type UpdateTaskDto = {
  /**
   * El titúlo de la tarea
   */
  title: string;
  /**
   * La descripción de la tarea
   */
  description: string;
};
