// This file is auto-generated by @hey-api/openapi-ts

export const TaskDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'number',
            description: 'El ID de la tarea'
        },
        title: {
            type: 'string',
            description: 'El titúlo de la tarea'
        },
        description: {
            type: 'string',
            description: 'Descrippcion de la tarea'
        },
        createdAt: {
            format: 'date-time',
            type: 'string',
            description: 'Fecha de creación de la tarea'
        }
    },
    required: ['id', 'title', 'description', 'createdAt']
} as const;

export const CreateTaskDtoSchema = {
    type: 'object',
    properties: {
        title: {
            type: 'string',
            description: 'El titúlo de la tarea'
        },
        description: {
            type: 'string',
            description: 'La descripción de la tarea'
        }
    },
    required: ['title', 'description']
} as const;

export const UpdateTaskDtoSchema = {
    type: 'object',
    properties: {
        title: {
            type: 'string',
            description: 'El titúlo de la tarea'
        },
        description: {
            type: 'string',
            description: 'La descripción de la tarea'
        }
    },
    required: ['title', 'description']
} as const;