// This file is auto-generated by @hey-api/openapi-ts

export type TaskDto = {
    /**
     * El ID de la tarea
     */
    id: number;
    /**
     * El titúlo de la tarea
     */
    title: string;
    /**
     * Descrippcion de la tarea
     */
    description: string;
    /**
     * Fecha de creación de la tarea
     */
    createdAt: string;
};

export type CreateTaskDto = {
    /**
     * El titúlo de la tarea
     */
    title: string;
    /**
     * La descripción de la tarea
     */
    description: string;
};

export type UpdateTaskDto = {
    /**
     * El titúlo de la tarea
     */
    title: string;
    /**
     * La descripción de la tarea
     */
    description: string;
};

export type AppControllerGetHelloResponse = (unknown);

export type AppControllerGetHelloError = unknown;

export type TasksControllerGetTasksResponse = (Array<TaskDto>);

export type TasksControllerGetTasksError = (unknown);

export type TasksControllerCreateTaskData = {
    body: CreateTaskDto;
};

export type TasksControllerCreateTaskResponse = (TaskDto);

export type TasksControllerCreateTaskError = (unknown);

export type TasksControllerGetTaskData = {
    path: {
        id: number;
    };
};

export type TasksControllerGetTaskResponse = (TaskDto);

export type TasksControllerGetTaskError = (unknown);

export type TasksControllerUpdateTaskData = {
    body: UpdateTaskDto;
    path: {
        id: number;
    };
};

export type TasksControllerUpdateTaskResponse = (TaskDto);

export type TasksControllerUpdateTaskError = (unknown);

export type TasksControllerDeleteTaskData = {
    path: {
        id: number;
    };
};

export type TasksControllerDeleteTaskResponse = (TaskDto);

export type TasksControllerDeleteTaskError = (unknown);